:showtitle:
:toc: left
:icons: font

= steno

This repo contains an in-progress prototype interface for sagas based on distributed sagas.

Our sagas comprise a directed acyclic graph of possibly-reversible actions, similar to distributed sagas.  There are two main functional pieces: an interface for constructing the graph and an execution engine for carrying out the actions described by the graph.  There are many subparts to this problem.

== What's this?

"Workflow" is a general term for an abstraction that manages execution of complex, multi-step processes.  The implementation here is heavily based on https://www.youtube.com/watch?v=0UTOLRTwOX0[Distributed Sagas as described by Caitie McAffrey].

Why is this useful?  See https://rfd.oxide.computer/107[RFD 107 "OXCP Workflows Engine"].  The basic idea here is to decompose the complex work of the control plane into:

* comparatively simple actions provided by stateless services like the server agent, switch agent, etc.  ("Stateless" here refers to database state.  In fact, these services mostly exist to expose the very real state of the systems they run on!)
* composition of these actions into sagas, which we hope will also be relatively simple because of the way the actions and undo actions are defined
* execution of the saga (dealing with unwinding, etc.), which we implement in one place with good mechanisms for observing progress, controlling execution, etc.  That's what this crate provides.

The hope is that with a strong foundation here, we can move quickly with future work and build a reliable, predictable, observable system.

== Status

Here's what exists so far:

* an interface (`SagaActionFunc`) for consumers to define their own "actions" using regular functions to implement the action and the undo action
* an interface (`SagaTemplateBuilder`) for building a saga (DAG) from these actions
* an execution engine (`SagaExecutor`) that executes the action
* features:
** actions can share state using arbitrary serializable types (dynamically-checked, unfortunately)
** persistence and recovery: execution state is serialized to a log that can be recovered to resume execution after a crash
** unwinding: if an action fails, all nodes are unwound (basically, undo actions are executed for nodes whose actions completed; it's more complicated for nodes whose actions _may_ have run)
** injecting errors into an arbitrary node
** fine-grained status reporting (status of each action)
* a demo program (`examples/demo-provision`) to exercise all of this with a toy saga that resembles Instance provisioning

There are lots of caveats:

* All experimentation and testing uses a toy saga that doesn't actually do anything.
* The code is prototype-quality (i.e., mediocre).  There's tremendous room for cleanup and improvement.
* There's virtually no automated testing yet.
* There's no usage documentation yet.
* There are many important considerations not yet addressed.  To start with:
** updates and versioning: how a saga's code gets packaged, updated, etc.; and how the code and state get versioned
** Subsagas: it's totally possible for saga actions to create other sagas, which is important because composeability is important for our use case.  However, doing so is not idempotent, and won't necessarily do the right thing in the event of failures.
* Serialization format for the log is a little dubious -- see the event_type enum.

Major risks and open questions:

* Does this abstraction make sense?  Let's try prototyping it in oxide-api-prototype.
* Failover (or "high availability execution")


Future feature ideas include:

* execution parameters
* control: pause/unpause, abort, concurrencly limits, single-step, breakpoints
* canarying
* other policies around nodes with no undo actions (e.g., pause and notify an operator, then resume the saga if directed; fail-forward only)
* a notion of "scope" or "blast radius" for a saga so that a larger system can schedule sagas in a way that preserves overall availability
* better compile-time type checking, so that you cannot add a node to a saga graph that uses data not provided by one of its ancestors

== Divergence from distributed sagas

As mentioned above, this implementation is very heavily based on distributed sagas.  There are a few important considerations not covered in the talk referenced above:

* How do actions share state with one another?  (If an early step allocates an IP address, how can a later step use that IP address to plumb up a network interface?)
* How do you provide high-availability execution (at least, execution that automatically continues in the face of failure of the saga execution coordinator (SEC))?  Equivalently: how do you ensure that two SEC instances aren't working concurrently on the same saga?

We're also generalizing the idea in a few ways:

* A node need not have an undo action (compensating request).  We might provide policy that can cause the saga to pause and wait for an operator, or to only fail-forward.
* See above: canarying, scope, blast radius, etc.

The terminology used in the original talk seems to come from microservices and databases.  We found some of these confusing and chose some different terms:

[cols="1,2,1,2",options="header"]
|===
|Our term
|What it means
|Distributed Sagas term
|Why we picked another term

|Action
|A node in the saga graph, or (equivalently) the user-defined action taken when the executor "executes" that node of the graph
|Request
|"Request" suggests an RPC or an HTTP request.  Our actions may involve neither of those or they may comprise many requests.

|Undo action
|The user-defined action taken for a node whose action needs to be logically reversed
|Compensating request
|See "Action" above.  We could have called this "compensating action" but "undo" felt more evocative of what's happening.

|Fail/Failed
|The result of an action that was not successful
|Abort/Aborted
|"Abort" can be used to mean a bunch of things, like maybe that an action failed, or that it was cancelled while it was still running, or that it was undone.  These are all different things so we chose different terms to avoid confusion.

|Cancel/Cancelled
|What happens to a node whose action needs to be logically reversed.  This might involve doing nothing (if the action never ran), executing the undo action (if the action previously succeeded), or something a bit more complicated.
|Undo
|"Cancel" might suggest to a reader that we stopped an action while it was in progress.  That's not what it means here.  Plus, we avoid the awkward "canceled" vs. "cancelled" debate.

|===
