# ---------------------------------------------------------------------------
# Stable features that we customize locally
# ---------------------------------------------------------------------------
max_width = 80
use_small_heuristics = "max"
edition = "2018"

unstable_features = true
normalize_comments = true
#format_strings = true
#comment_width = 80
# format_strings = true
